### PR TITLE
Replacing Tut with Mdoc

### LINKED ISSUE #72: Use mdoc for the microsite
`tut` is no longer maintained and has issues with new versions of `sbt-microsites`.

### PR DESCRIPTION
**Pull request by gvolpe**
closes #72

### CODE REVIEW

**Comment by kubukoz** [comment]
That... wasn't that hard! I should get to it in my projects...

**Comment by kubukoz** [comment]
BTW https://console4cats.profunktor.dev/ doesn't work...

**Comment by gvolpe** [comment]
Yeah... Some issue with the CNAME file, trying to fix it...

**Comment by gvolpe** [comment]
It should be back soon. Took me a while to figure it out... This setting was missing (not needed for `tut`):

```
micrositeExtraMdFilesOutput := (resourceManaged in Compile).value / "jekyll",
```

**Comment by gvolpe** [comment]
Well... I also changed the DNS configuration using the recommended CNAME record instead of an A record and it doesn't work... Though, I don't want to deal with GitHub customer support. I'll change it back to using A records.

**Comment by gvolpe** [comment]
Okay... make sure you also have `jekyll >= 4.0.0` installed

**Pull request merged**
